controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_note_list:
    path: '/notes/list'
    controller: 'App\Controller\NoteController::list'
    methods: ['GET']